---
- name: Remove existing /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: Create new resolv.conf from template
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart systemd-resolved